# Generated by Django 3.1.7 on 2021-04-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
