# Generated by Django 3.1.7 on 2021-04-28 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210428_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='mobileno',
            new_name='phone',
        ),
    ]
