# Generated by Django 3.1.7 on 2021-04-29 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210428_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='gal',
            fields=[
                ('ino', models.AutoField(primary_key=True, serialize=False)),
                ('iname', models.CharField(max_length=100)),
                ('gimg', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
