# Generated by Django 3.1.7 on 2021-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_gal'),
    ]

    operations = [
        migrations.CreateModel(
            name='keyfeatimg',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.CharField(max_length=100)),
                ('kimg', models.ImageField(default='', upload_to='home/images')),
            ],
        ),
    ]
