# Generated by Django 3.1.7 on 2021-05-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_keyfeatimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField(max_length=5000)),
                ('slug', models.CharField(max_length=500)),
                ('author', models.CharField(max_length=100)),
                ('img', models.ImageField(default='', upload_to='home/images')),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
        ),
    ]
